class DocumentTypeConfig {
  final String category;
  final List<String> required;
  final List<String> optional;
  final String description;

  const DocumentTypeConfig({
    required this.category,
    required this.required,
    required this.optional,
    required this.description,
  });
}

/// Presentation metadata for the Legal Writing form. Keys intentionally match
/// the prompt placeholders and document configuration exactly.
const Map<String, String> documentFieldLabels = {
  'senderName': 'Sender name',
  'senderAddress': 'Sender address',
  'senderPhone': 'Sender phone number',
  'recipientName': 'Recipient name',
  'recipientAddress': 'Recipient address',
  'issueDescription': 'Issue description',
  'legalViolation': 'Legal basis / right involved',
  'demands': 'Demand or remedy sought',
  'complianceDeadline': 'Compliance deadline',
  'previousNotices': 'Previous notices',
  'evidenceList': 'Evidence available',
  'complainantName': 'Complainant name',
  'complainantAddress': 'Complainant address',
  'complainantPhone': 'Complainant phone number',
  'complainantEmail': 'Complainant email',
  'oppositePartyName': 'Opposite party name',
  'oppositePartyAddress': 'Opposite party address',
  'complaintCategory': 'Product or service category',
  'purchaseDate': 'Purchase / transaction date',
  'amountPaid': 'Amount paid',
  'complaintDetails': 'Complaint details',
  'reliefSought': 'Relief sought',
  'previousComplaints': 'Previous complaints',
  'accusedName': 'Accused name',
  'accusedAddress': 'Accused address',
  'incidentDate': 'Incident date',
  'incidentPlace': 'Incident place',
  'incidentDescription': 'Incident description',
  'crimeType': 'Nature of complaint',
  'witnessDetails': 'Witness details',
  'unlawfulActivity': 'Conduct to stop',
  'legalBasis': 'Legal basis / right involved',
  'demandAction': 'Required action',
  'deadlineDays': 'Compliance deadline (days)',
  'previousWarnings': 'Previous warnings',
  'demandAmount': 'Demand amount',
  'demandReason': 'Reason for demand',
  'paymentDeadline': 'Payment deadline',
  'previousDemands': 'Previous demands',
  'supportingDocuments': 'Supporting documents',
  'landlordName': 'Landlord name',
  'landlordAddress': 'Landlord address',
  'landlordPhone': 'Landlord phone number',
  'tenantName': 'Tenant name',
  'tenantAddress': 'Tenant address',
  'tenantPhone': 'Tenant phone number',
  'propertyAddress': 'Property address',
  'propertyType': 'Property type',
  'monthlyRent': 'Monthly rent',
  'leaseDuration': 'Lease duration',
  'startDate': 'Start date',
  'securityDeposit': 'Security deposit',
  'maintenanceResponsibility': 'Maintenance responsibility',
  'specialClauses': 'Special clauses',
  'providerName': 'Service provider name',
  'providerAddress': 'Service provider address',
  'providerPhone': 'Service provider phone number',
  'clientName': 'Client name',
  'clientAddress': 'Client address',
  'clientPhone': 'Client phone number',
  'serviceDescription': 'Services and scope',
  'serviceDuration': 'Service duration / timeline',
  'fee': 'Fee',
  'paymentSchedule': 'Payment schedule',
  'terminationNotice': 'Termination notice',
  'deliverables': 'Deliverables',
  'milestones': 'Milestones',
  'disclosingParty': 'Disclosing party',
  'disclosingPartyAddress': 'Disclosing party address',
  'receivingParty': 'Receiving party',
  'receivingPartyAddress': 'Receiving party address',
  'confidentialInformation': 'Confidential information',
  'purposeOfDisclosure': 'Permitted purpose',
  'termOfAgreement': 'Agreement duration',
  'jurisdiction': 'Jurisdiction',
  'exceptions': 'Confidentiality exclusions',
  'returnOfMaterials': 'Return / destruction requirements',
  'employerName': 'Employer name',
  'employerAddress': 'Employer address',
  'employeeName': 'Employee name',
  'employeeAddress': 'Employee address',
  'position': 'Position',
  'salary': 'Salary',
  'workHours': 'Working hours',
  'jobDescription': 'Duties and responsibilities',
  'benefits': 'Benefits / leave',
  'probationPeriod': 'Probation period',
  'nonCompeteClause': 'Non-compete clause',
  'freelancerName': 'Freelancer name',
  'freelancerAddress': 'Freelancer address',
  'projectDescription': 'Project scope',
  'timeline': 'Timeline',
  'paymentTerms': 'Payment terms',
  'totalFee': 'Total fee',
  'revisionPolicy': 'Revision policy',
  'intellectualProperty': 'Intellectual-property ownership',
  'sellerName': 'Seller name',
  'sellerAddress': 'Seller address',
  'buyerName': 'Buyer name',
  'buyerAddress': 'Buyer address',
  'itemDescription': 'Property / goods description',
  'salePrice': 'Sale consideration',
  'paymentMethod': 'Payment terms',
  'deliveryDate': 'Delivery / possession date',
  'conditionOfItem': 'Condition / status of property or goods',
  'propertyOrGoodsLocation': 'Property / goods location',
  'advanceAmount': 'Advance amount',
  'balanceAmount': 'Balance amount',
  'possessionOrDeliveryTerms': 'Possession / delivery terms',
  'titleOrOwnershipRepresentations': 'Title / ownership representations',
  'documentsToBeProvided': 'Documents to be provided',
  'taxesAndCharges': 'Taxes / charges',
  'terminationTerms': 'Termination terms',
  'disputeResolution': 'Dispute resolution',
  'otherTerms': 'Other supplied terms',
  'firmName': 'Firm name',
  'businessAddress': 'Registered / principal office',
  'partner1Name': 'First partner name',
  'partner1Address': 'First partner address',
  'partner2Name': 'Second partner name',
  'partner2Address': 'Second partner address',
  'businessNature': 'Nature of business',
  'capitalContribution': 'Capital contribution',
  'profitSharingRatio': 'Profit / loss sharing',
  'commencementDate': 'Commencement date',
  'partnerContactDetails': 'Partner contact details',
  'dutiesAndResponsibilities': 'Duties / responsibilities',
  'drawings': 'Drawings terms',
  'bankingArrangements': 'Banking arrangements',
  'accountingArrangements': 'Accounting arrangements',
  'admissionRetirement': 'Admission / retirement terms',
  'party1Name': 'First party name',
  'party1Address': 'First party address',
  'party2Name': 'Second party name',
  'party2Address': 'Second party address',
  'purposeOfCollaboration': 'Purpose',
  'termDuration': 'Term duration',
  'responsibilities': 'Responsibilities',
  'confidentiality': 'Confidentiality terms',
  'governingLaw': 'Governing law',
  'commercialTerms': 'Commercial terms',
  'paymentOrInvestment': 'Payment / investment',
  'bindingNature': 'Binding / non-binding intention',
  'signatoryDetails': 'Signatory details',
  'deponentName': 'Deponent name',
  'deponentAddress': 'Deponent address',
  'deponentAge': 'Deponent age',
  'affirmationContent': 'Statements / facts affirmed',
  'purpose': 'Purpose',
  'place': 'Place',
  'date': 'Date',
  'notaryDetails': 'Notary details',
  'currentAddress': 'Current address',
  'durationAtAddress': 'Duration at current address',
  'previousAddress': 'Previous address',
  'oldName': 'Current / old name',
  'newName': 'New name',
  'reasonForChange': 'Reason for name change',
  'spouseName': 'Spouse name',
  'dateOfBirth': 'Date of birth',
  'annualIncome': 'Annual income',
  'incomeSource': 'Income sources',
  'employerOrBusiness': 'Employer / business',
  'monthlyIncome': 'Monthly income',
  'otherIncome': 'Other income',
  'financialDetails': 'Other financial details',
  'district': 'District',
  'state': 'State',
  'productOrService': 'Product / service',
  'transactionDetails': 'Transaction details',
  'invoiceOrOrderDetails': 'Invoice / order details',
  'deficiencyOrUnfairPractice': 'Deficiency / defect / unfair practice',
  'chronologyOfEvents': 'Chronology of events',
  'communications': 'Prior communications / complaints',
  'financialLoss': 'Financial loss',
  'mentalHarassmentDetails': 'Mental harassment details',
  'compensationRequested': 'Compensation requested',
  'refundReplacementOrOtherRelief': 'Refund / replacement / other relief',
  'jurisdictionDetails': 'Jurisdiction details',
  'advocateName': 'Advocate name',
  'advocateAddress': 'Advocate address',
  'courtName': 'Court / tribunal',
  'caseNumber': 'Case number',
  'caseType': 'Case details',
  'authorityGranted': 'Authority granted',
  'advocateAuthorizationTerms': 'Advocate authorization terms',
  'applicantName': 'Applicant name',
  'applicantAddress': 'Applicant address',
  'respondentOrState': 'Respondent / State',
  'firNumber': 'FIR number',
  'policeStation': 'Police station',
  'offense': 'Alleged offences / supplied sections',
  'arrestDate': 'Arrest date',
  'custodyDetails': 'Custody details',
  'factualBackground': 'Factual background',
  'groundsForBail': 'Grounds for bail',
  'personalCircumstances': 'Personal circumstances',
  'previousCases': 'Previous cases',
  'proposedConditions': 'Proposed bail conditions',
  'prayer': 'Prayer',
  'advocateDetails': 'Advocate details',
  // -- Batch 3: Appeal Letter (21) --
  'appellantName': 'Appellant name',
  'appellantAddress': 'Appellant address',
  'appellantPhone': 'Appellant phone number',
  'respondentName': 'Respondent name',
  'respondentAddress': 'Respondent address',
  'orderDate': 'Order / judgment date',
  'orderDetails': 'Order details',
  'decisionChallenged': 'Decision being challenged',
  'relevantFacts': 'Relevant facts',
  'groundsOfAppeal': 'Grounds of appeal',
  'limitationDelayInformation': 'Limitation / delay explanation',
  'advocateOrAppellantDetails': 'Advocate / appellant details',
  // -- Batch 3: Will / Testament (22) --
  'testatorName': 'Testator full name',
  'testatorAddress': 'Testator address',
  'testatorAge': 'Testator age',
  'familyLegalHeirInformation': 'Family / legal heir information',
  'beneficiaries': 'Beneficiaries',
  'assetsDistribution': 'Assets and distribution',
  'executorName': 'Executor name',
  'executorAddress': 'Executor address',
  'alternateExecutor': 'Alternate executor',
  'specificWishes': 'Specific wishes',
  'liabilitiesDebts': 'Liabilities / debts',
  'witness1Name': 'Witness 1 name',
  'witness1Address': 'Witness 1 address',
  'witness2Name': 'Witness 2 name',
  'witness2Address': 'Witness 2 address',
  // -- Batch 3: Power of Attorney (23) --
  'principalName': 'Principal name',
  'principalAddress': 'Principal address',
  'principalPhone': 'Principal phone number',
  'agentName': 'Agent / attorney name',
  'agentAddress': 'Agent address',
  'agentPhone': 'Agent phone number',
  'powersGranted': 'Powers granted',
  'effectiveDate': 'Effective date',
  'propertyTransactionDetails': 'Property / transaction details',
  'scopeOfAuthority': 'Scope of authority',
  'limitationsRestrictions': 'Limitations / restrictions',
  'duration': 'Duration',
  'revocationTerminationTerms': 'Revocation / termination terms',
  'consideration': 'Consideration',
  // -- Batch 3: Gift Deed (24) --
  'donorName': 'Donor name',
  'donorAddress': 'Donor address',
  'doneeName': 'Donee name',
  'doneeAddress': 'Donee address',
  'relationship': 'Relationship between donor and donee',
  'propertyAssetDetails': 'Property / asset details',
  'propertyDescription': 'Property description',
  'propertyLocation': 'Property location',
  'ownershipDetails': 'Ownership details',
  'giftValue': 'Gift value',
  'voluntaryNature': 'Voluntary nature of gift',
  'doneeAcceptance': 'Acceptance by donee',
  'possessionTransferDetails': 'Possession / transfer details',
  'encumbranceInformation': 'Encumbrance information',
  // -- Batch 3: Relinquishment Deed (25) --
  'grantorName': 'Grantor (relinquishing party) name',
  'grantorAddress': 'Grantor address',
  'grantorPhone': 'Grantor phone number',
  'beneficiaryName': 'Beneficiary name',
  'beneficiaryAddress': 'Beneficiary address',
  'beneficiaryPhone': 'Beneficiary phone number',
  'rightsRelinquished': 'Rights being relinquished',
  'reason': 'Reason for relinquishment',
  'voluntary': 'Voluntary declaration',
  'noCoercion': 'No coercion / free will declaration',
  'considerationAmount': 'Consideration amount',
  'considerationDetails': 'Consideration details',
  'transferredRights': 'Rights transferred to beneficiary',
  'futureClaimsWaived': 'Future claims waived',
  'originalOwner': 'Original owner',
  // -- Batch 3: Resignation Letter (26) --
  'companyName': 'Company name',
  'companyAddress': 'Company address',
  'hrContactName': 'HR contact name',
  'department': 'Department',
  'dateOfJoining': 'Date of joining',
  'yearsOfService': 'Years of service',
  'resignationDate': 'Resignation date',
  'lastWorkingDay': 'Last working day',
  'noticePeriodDays': 'Notice period (days)',
  'reasonForResignation': 'Reason for resignation',
  'transitionHelp': 'Transition help offered',
  'knowledgeTransfer': 'Knowledge transfer plan',
  'finalTasks': 'Final tasks to complete',
  'gratitudeStatement': 'Gratitude statement',
  'experienceGained': 'Experience / learnings gained',
  'employeePhone': 'Employee phone number',
  // -- Batch 3: Termination Letter (27) --
  'companyPhone': 'Company phone number',
  'employeeID': 'Employee ID',
  'designation': 'Designation',
  'terminationDate': 'Termination effective date',
  'terminationReason': 'Reason for termination',
  'lastSalaryMonth': 'Last salary month',
  'finalSalaryAmount': 'Final salary amount',
  'gratuityAmount': 'Gratuity amount',
  'leaveEncashment': 'Leave encashment',
  'otherBenefits': 'Other benefits',
  'netAmount': 'Net settlement amount',
  'paymentDate': 'Settlement payment date',
  'itemsToReturn': 'Company items to return',
  'returnDate': 'Return deadline date',
  'referenceLetter': 'Reference letter status',
  'serviceCertificate': 'Service certificate status',
  // -- Batch 3: Experience Letter (28) --
  'totalDuration': 'Total employment duration',
  'lastSalary': 'Last drawn salary',
  'jobTitle': 'Job title',
  'reportingTo': 'Reporting manager',
  'technicalSkills': 'Technical skills',
  'softSkills': 'Soft skills',
  'performanceRating': 'Performance rating',
  'strengths': 'Key strengths',
  'achievements': 'Notable achievements',
  'conductRating': 'Conduct rating',
  'reliability': 'Reliability assessment',
  'punctuality': 'Punctuality assessment',
  'reasonForLeaving': 'Reason for leaving',
  'wouldRehire': 'Would rehire?',
  'recommendationStatement': 'Recommendation statement',
  'contactForReference': 'Reference contact person',
  'referencePhone': 'Reference contact phone',
  // -- Batch 3: Offer Letter (29) --
  'candidateName': 'Candidate name',
  'candidateAddress': 'Candidate address',
  'candidateEmail': 'Candidate email',
  'candidatePhone': 'Candidate phone number',
  'workLocation': 'Work location',
  'employmentType': 'Employment type',
  'joiningDate': 'Joining date',
  'annualSalary': 'Annual salary (CTC)',
  'monthlySalary': 'Monthly salary (in-hand)',
  'bonusStructure': 'Bonus structure',
  'healthInsurance': 'Health insurance',
  'retirementBenefits': 'Retirement / PF benefits',
  'leavePolicy': 'Leave policy',
  'workingHours': 'Working hours',
  'travelRequirement': 'Travel requirement',
  'confidentialityClause': 'Confidentiality / NDA clause',
  'acceptanceDate': 'Acceptance deadline (date)',
  'acceptanceDays': 'Acceptance deadline (days)',
  'reportingInstructions': 'Reporting instructions',
  'keyObjectives': 'Key objectives / KPIs',
};

const Map<String, DocumentTypeConfig> documentTypeFields = {
  // COMPLAINTS & NOTICES
  'legal_notice': DocumentTypeConfig(
    category: 'Complaints & Notices',
    required: [
      'senderName',
      'senderAddress',
      'senderPhone',
      'recipientName',
      'recipientAddress',
      'issueDescription',
      'legalViolation',
      'demands',
      'complianceDeadline'
    ],
    optional: ['previousNotices', 'evidenceList'],
    description: 'Formal legal notice for dispute resolution',
  ),
  'consumer_complaint': DocumentTypeConfig(
    category: 'Complaints & Notices',
    required: [
      'complainantName',
      'complainantAddress',
      'complainantPhone',
      'oppositePartyName',
      'oppositePartyAddress',
      'complaintCategory',
      'purchaseDate',
      'amountPaid',
      'complaintDetails',
      'reliefSought'
    ],
    optional: ['complainantEmail', 'previousComplaints'],
    description: 'Consumer forum complaint against goods/services',
  ),
  'police_complaint': DocumentTypeConfig(
    category: 'Complaints & Notices',
    required: [
      'complainantName',
      'complainantAddress',
      'complainantPhone',
      'accusedName',
      'accusedAddress',
      'incidentDate',
      'incidentPlace',
      'incidentDescription',
      'crimeType'
    ],
    optional: ['complainantEmail', 'evidenceList', 'witnessDetails'],
    description: 'FIR registration for criminal offense',
  ),
  'cease_desist': DocumentTypeConfig(
    category: 'Complaints & Notices',
    required: [
      'senderName',
      'senderAddress',
      'senderPhone',
      'recipientName',
      'recipientAddress',
      'unlawfulActivity',
      'legalBasis',
      'demandAction',
      'deadlineDays'
    ],
    optional: ['previousWarnings', 'evidenceList'],
    description: 'Cease and desist notice for unlawful activity',
  ),
  'demand_letter': DocumentTypeConfig(
    category: 'Complaints & Notices',
    required: [
      'senderName',
      'senderAddress',
      'senderPhone',
      'recipientName',
      'recipientAddress',
      'demandAmount',
      'demandReason',
      'legalBasis',
      'paymentDeadline'
    ],
    optional: ['previousDemands', 'supportingDocuments'],
    description: 'Formal demand for payment or performance',
  ),

  // AGREEMENTS & CONTRACTS
  'rent_agreement': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'landlordName',
      'landlordAddress',
      'landlordPhone',
      'tenantName',
      'tenantAddress',
      'tenantPhone',
      'propertyAddress',
      'propertyType',
      'monthlyRent',
      'leaseDuration',
      'startDate',
      'securityDeposit'
    ],
    optional: ['maintenanceResponsibility', 'specialClauses'],
    description: 'Residential or commercial rental agreement',
  ),
  'service_agreement': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'providerName',
      'providerAddress',
      'providerPhone',
      'clientName',
      'clientAddress',
      'clientPhone',
      'serviceDescription',
      'serviceDuration',
      'fee',
      'paymentSchedule',
      'terminationNotice'
    ],
    optional: ['deliverables', 'milestones'],
    description: 'Service provider agreement',
  ),
  'nda_confidentiality': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'disclosingParty',
      'disclosingPartyAddress',
      'receivingParty',
      'receivingPartyAddress',
      'confidentialInformation',
      'purposeOfDisclosure',
      'termOfAgreement',
      'jurisdiction'
    ],
    optional: ['exceptions', 'returnOfMaterials'],
    description: 'Non-disclosure agreement for confidential information',
  ),
  'employment_contract': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'employerName',
      'employerAddress',
      'employeeName',
      'employeeAddress',
      'position',
      'startDate',
      'salary',
      'workHours',
      'jobDescription',
      'terminationNotice'
    ],
    optional: ['benefits', 'probationPeriod', 'nonCompeteClause'],
    description: 'Employment contract between employer and employee',
  ),
  'freelance_contract': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'clientName',
      'clientAddress',
      'freelancerName',
      'freelancerAddress',
      'projectDescription',
      'deliverables',
      'timeline',
      'paymentTerms',
      'totalFee'
    ],
    optional: ['milestones', 'revisionPolicy', 'intellectualProperty'],
    description: 'Freelance project contract',
  ),
  'sale_agreement': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'sellerName',
      'sellerAddress',
      'buyerName',
      'buyerAddress',
      'itemDescription',
      'salePrice',
      'paymentMethod',
      'deliveryDate',
      'conditionOfItem'
    ],
    optional: [
      'propertyOrGoodsLocation',
      'advanceAmount',
      'balanceAmount',
      'possessionOrDeliveryTerms',
      'titleOrOwnershipRepresentations',
      'documentsToBeProvided',
      'taxesAndCharges',
      'defaultClause',
      'terminationTerms',
      'disputeResolution',
      'witnessDetails',
      'otherTerms',
      'warranty',
      'inspectionPeriod'
    ],
    description: 'Sale/purchase agreement for goods or property',
  ),
  'partnership_deed': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'firmName',
      'businessAddress',
      'partner1Name',
      'partner1Address',
      'partner2Name',
      'partner2Address',
      'businessNature',
      'capitalContribution',
      'profitSharingRatio',
      'commencementDate'
    ],
    optional: [
      'partnerContactDetails',
      'dutiesAndResponsibilities',
      'drawings',
      'bankingArrangements',
      'accountingArrangements',
      'admissionRetirement',
      'dissolutionClause',
      'disputeResolution',
      'duration',
      'witnessDetails',
      'otherTerms',
      'additionalPartners',
      'decisionMaking'
    ],
    description: 'Partnership deed for business formation',
  ),
  'mou_term_sheet': DocumentTypeConfig(
    category: 'Agreements & Contracts',
    required: [
      'party1Name',
      'party1Address',
      'party2Name',
      'party2Address',
      'purposeOfCollaboration',
      'termDuration',
      'responsibilities',
      'confidentiality',
      'governingLaw'
    ],
    optional: [
      'background',
      'scope',
      'commercialTerms',
      'paymentOrInvestment',
      'milestones',
      'timelines',
      'exclusivity',
      'intellectualProperty',
      'termination',
      'disputeResolution',
      'bindingNature',
      'validity',
      'signatoryDetails',
      'financialTerms'
    ],
    description: 'Memorandum of understanding or term sheet',
  ),

  // AFFIDAVITS & DECLARATIONS
  'general_affidavit': DocumentTypeConfig(
    category: 'Affidavits & Declarations',
    required: [
      'deponentName',
      'deponentAddress',
      'deponentAge',
      'affirmationContent',
      'purpose',
      'place',
      'date'
    ],
    optional: [
      'declaration',
      'supportingDetails',
      'supportingDocuments',
      'verification',
      'witnessDetails',
      'notaryDetails'
    ],
    description: 'General purpose affidavit',
  ),
  'address_proof_affidavit': DocumentTypeConfig(
    category: 'Affidavits & Declarations',
    required: [
      'deponentName',
      'deponentAddress',
      'deponentAge',
      'currentAddress',
      'durationAtAddress',
      'purpose',
      'place',
      'date'
    ],
    optional: [
      'previousAddress',
      'addressHistory',
      'supportingFactsOrDocuments',
      'declaration',
      'verification',
      'witnessDetails',
      'notaryDetails',
      'landlordDetails'
    ],
    description: 'Affidavit for address proof',
  ),
  'name_change_affidavit': DocumentTypeConfig(
    category: 'Affidavits & Declarations',
    required: [
      'deponentName',
      'deponentAddress',
      'deponentAge',
      'oldName',
      'newName',
      'reasonForChange',
      'place',
      'date'
    ],
    optional: [
      'fatherName',
      'motherName',
      'spouseName',
      'dateOfBirth',
      'declaration',
      'verification',
      'witnessDetails',
      'notaryDetails',
      'supportingDocuments'
    ],
    description: 'Affidavit for name change',
  ),
  'income_affidavit': DocumentTypeConfig(
    category: 'Affidavits & Declarations',
    required: [
      'deponentName',
      'deponentAddress',
      'deponentAge',
      'annualIncome',
      'incomeSource',
      'purpose',
      'place',
      'date'
    ],
    optional: [
      'occupation',
      'employerOrBusiness',
      'monthlyIncome',
      'otherIncome',
      'financialDetails',
      'declaration',
      'verification',
      'witnessDetails',
      'notaryDetails',
      'employmentDetails',
      'otherIncomeSources'
    ],
    description: 'Affidavit declaring income for official purposes',
  ),

  // COURT & LEGAL FILINGS
  'consumer_court_complaint': DocumentTypeConfig(
    category: 'Court & Legal Filings',
    required: [
      'complainantName',
      'complainantAddress',
      'complainantPhone',
      'oppositePartyName',
      'oppositePartyAddress',
      'district',
      'state',
      'complaintCategory',
      'purchaseDate',
      'amountPaid',
      'complaintDetails',
      'reliefSought'
    ],
    optional: [
      'complainantEmail',
      'productOrService',
      'transactionDetails',
      'invoiceOrOrderDetails',
      'deficiencyOrUnfairPractice',
      'chronologyOfEvents',
      'communications',
      'evidenceList',
      'financialLoss',
      'mentalHarassmentDetails',
      'compensationRequested',
      'refundReplacementOrOtherRelief',
      'jurisdictionDetails',
      'verification',
      'place',
      'date',
      'previousComplaints'
    ],
    description: 'Consumer court complaint filing',
  ),
  'vakalatnama': DocumentTypeConfig(
    category: 'Court & Legal Filings',
    required: [
      'clientName',
      'clientAddress',
      'advocateName',
      'advocateAddress',
      'courtName',
      'place',
      'date'
    ],
    optional: [
      'caseNumber',
      'caseType',
      'parties',
      'authorityGranted',
      'advocateAuthorizationTerms',
      'signatoryDetails',
      'witnessDetails',
      'advocatePhone',
      'advocateEnrollmentNumber'
    ],
    description: 'Vakalatnama - power to advocate to represent in court',
  ),
  'bail_application': DocumentTypeConfig(
    category: 'Court & Legal Filings',
    required: ['accusedName', 'courtName', 'groundsForBail'],
    optional: [
      'applicantName',
      'applicantAddress',
      'accusedAddress',
      'respondentOrState',
      'firNumber',
      'caseNumber',
      'policeStation',
      'offense',
      'arrestDate',
      'custodyDetails',
      'factualBackground',
      'personalCircumstances',
      'previousCases',
      'previousBailApplications',
      'proposedConditions',
      'prayer',
      'place',
      'date',
      'advocateDetails',
      'signatoryDetails',
      'suretyDetails',
      'bailType'
    ],
    description: 'Bail application for accused person',
  ),
  'appeal_letter': DocumentTypeConfig(
    category: 'Court & Legal Filings',
    required: [
      'appellantName',
      'respondentName',
      'courtName',
      'caseNumber',
      'orderDate',
      'decisionChallenged',
      'relevantFacts',
      'groundsOfAppeal',
      'reliefSought'
    ],
    optional: ['appellantAddress', 'appellantPhone', 'respondentAddress', 'orderDetails', 'supportingDocuments', 'limitationDelayInformation', 'prayer', 'place', 'date', 'advocateOrAppellantDetails'],
    description: 'Appeal letter against court judgment',
  ),

  // PERSONAL & PROPERTY
  'will_testament': DocumentTypeConfig(
    category: 'Personal & Property',
    required: [
      'testatorName',
      'testatorAddress',
      'familyLegalHeirInformation',
      'beneficiaries',
      'assetsDistribution',
      'executorName',
      'place', 'date'
    ],
    optional: ['testatorAge', 'executorAddress', 'alternateExecutor', 'specificWishes', 'liabilitiesDebts', 'witness1Name', 'witness1Address', 'witness2Name', 'witness2Address'],
    description: 'Last will and testament',
  ),
  'power_of_attorney': DocumentTypeConfig(
    category: 'Personal & Property',
    required: [
      'principalName',
      'principalAddress',
      'agentName',
      'agentAddress',
      'purpose',
      'powersGranted',
      'effectiveDate', 'place', 'date'
    ],
    optional: ['principalPhone', 'agentPhone', 'propertyTransactionDetails', 'scopeOfAuthority', 'limitationsRestrictions', 'duration', 'revocationTerminationTerms', 'consideration', 'witness1Name', 'witness1Address', 'witness2Name', 'witness2Address'],
    description: 'Power of attorney document',
  ),
  'gift_deed': DocumentTypeConfig(
    category: 'Personal & Property',
    required: [
      'donorName',
      'donorAddress',
      'doneeName',
      'doneeAddress',
      'propertyDescription',
      'place', 'date'
    ],
    optional: ['relationship', 'propertyAssetDetails', 'propertyLocation', 'ownershipDetails', 'giftValue', 'voluntaryNature', 'doneeAcceptance', 'possessionTransferDetails', 'encumbranceInformation', 'witness1Name', 'witness1Address', 'witness2Name', 'witness2Address'],
    description: 'Gift deed for property transfer',
  ),
  'relinquishment_deed': DocumentTypeConfig(
    category: 'Personal & Property',
    required: [
      'grantorName',
      'grantorAddress',
      'beneficiaryName',
      'beneficiaryAddress',
      'propertyType',
      'propertyDescription',
      'rightsRelinquished', 'reason', 'voluntary', 'noCoercion',
      'transferredRights', 'futureClaimsWaived', 'place', 'date',
      'witness1Name', 'witness1Address', 'witness2Name', 'witness2Address'
    ],
    optional: ['grantorPhone', 'beneficiaryPhone', 'propertyLocation', 'originalOwner', 'considerationAmount', 'considerationDetails'],
    description: 'Relinquishment deed for property share',
  ),

  // HR & EMPLOYMENT
  'resignation_letter': DocumentTypeConfig(
    category: 'HR & Employment',
    required: [
      'employeeName',
      'employeeAddress',
      'companyName',
      'companyAddress',
      'position',
      'resignationDate', 'lastWorkingDay'
    ],
    optional: ['employeePhone', 'hrContactName', 'department', 'dateOfJoining', 'yearsOfService', 'noticePeriodDays', 'reasonForResignation', 'transitionHelp', 'knowledgeTransfer', 'finalTasks', 'gratitudeStatement', 'experienceGained'],
    description: 'Formal resignation letter',
  ),
  'termination_letter': DocumentTypeConfig(
    category: 'HR & Employment',
    required: [
      'companyName',
      'companyAddress',
      'employeeName',
      'employeeAddress',
      'designation',
      'terminationDate',
      'lastWorkingDay'
    ],
    optional: ['hrContactName', 'companyPhone', 'employeeID', 'department', 'dateOfJoining', 'terminationReason', 'noticePeriodDays', 'lastSalaryMonth', 'finalSalaryAmount', 'gratuityAmount', 'leaveEncashment', 'otherBenefits', 'netAmount', 'paymentDate', 'itemsToReturn', 'returnDate', 'referenceLetter', 'serviceCertificate'],
    description: 'Employment termination letter',
  ),
  'experience_letter': DocumentTypeConfig(
    category: 'HR & Employment',
    required: [
      'companyName',
      'companyAddress',
      'employeeName',
      'designation', 'dateOfJoining', 'dateOfLeaving'
    ],
    optional: ['companyPhone', 'department', 'employeeID', 'totalDuration', 'lastSalary', 'jobTitle', 'responsibilities', 'reportingTo', 'technicalSkills', 'softSkills', 'performanceRating', 'strengths', 'achievements', 'conductRating', 'reliability', 'punctuality', 'reasonForLeaving', 'wouldRehire', 'recommendationStatement', 'contactForReference', 'referencePhone', 'place', 'date'],
    description: 'Experience/employment certificate',
  ),
  'offer_letter': DocumentTypeConfig(
    category: 'HR & Employment',
    required: [
      'companyName',
      'companyAddress',
      'candidateName',
      'jobTitle',
      'workLocation',
      'employmentType', 'joiningDate'
    ],
    optional: ['companyPhone', 'candidateAddress', 'candidateEmail', 'candidatePhone', 'department', 'reportingTo', 'responsibilities', 'keyObjectives', 'probationPeriod', 'annualSalary', 'monthlySalary', 'bonusStructure', 'healthInsurance', 'retirementBenefits', 'leavePolicy', 'otherBenefits', 'workingHours', 'travelRequirement', 'confidentialityClause', 'acceptanceDate', 'acceptanceDays', 'reportingInstructions', 'place', 'date'],
    description: 'Job offer letter',
  ),
};
